# Site settings
title: "volent's blog"
email: "volent@volent.fr"
description: > 
  I am a french Fullstack developer actually working in Lyon (France).
  I love Linux, Python & Javascript and I will try to write about it.
baseurl: ""
url: "http://blog.volent.fr"
markdown: kramdown

social:
  twitter: "volent_"
  github:  "volnt"
  linkedin: "florentespanet"
  stackoverflow: "users/2437219/volent"
  rss: true

